# Setup
title: Investigating Poole 
tagline: Adapting The Jekyll Butler to learn
url: https://akmolteni.github.io/gju
paginate: 3
baseurl: ""
# permalink: pretty
permalink: /:year/:month/:day/:title/

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: AK Molteni
  url: https://akmolteni.github.io/
  email: private@private.com

# Custom vars
version: 1.0.0

# For github pages
website: https://akmolteni.github.io
baseurl: /gju

# Collection of Notes
collections:
  - notes
